feat(ui): Add a button to manually refresh the ports
JadKHaddad/serial-vau pull request #10
Opened 2024-09-27 21:02 UTC by fabianbernhart

manually refresh the ports in the ui #5

2024-09-28 08:43 UTC, JadKHaddad commented
Womit formatierst du?

2024-09-28 10:41 UTC, fabianbernhart commented
mit prettier habe es jetzt auf 2 spaces umgestellt

2024-09-28 13:05 UTC, JadKHaddad commented
Kannst du mal bitte die Fromat-Config in `.vscode` einstellen und mitcommiten?

2024-09-28 13:06 UTC, JadKHaddad commented
> mit prettier habe es jetzt auf 2 spaces umgestellt

Sichtbarer. Danke schön 👍

2024-09-29 08:45 UTC, JadKHaddad requested changes

2024-09-29 08:45 UTC, JadKHaddad commented on src/router/index.ts
> +  setInterval(() => {
Why are we polling?

2024-09-29 08:45 UTC, JadKHaddad commented on src/components/serial-port/SerialPort.vue
> +          openSerialPort({
Please rebase onto main

```javascript
@click="openSerialPort(port.name, port.lastUsedOpenOptions)"
```
- [refactor(open_serial_port)!](https://github.com/JadKHaddad/serial-vau/commit/c93836bb8551ef7269128ef89c50857e3b71ddfc)
- [feat(open_serial_port_options)!](https://github.com/JadKHaddad/serial-vau/commit/9168e57c344fdaf012fb9d3d4ac84e146f3c9248)

2024-10-09 18:44 UTC, closed without merging